OCAMLMAKEFILE = ../OCamlMakefile

#OCAMLOPT=ocamlopt.opt

#INCDIRS=../../poclow ../../poccore ../../pociface ../../extlib-1.3 ../../xml-light2.1 ../../cryptokit-1.2 ../../lua-ml
#LIBS=poclow xml-light extLib str nums lua-std poccore pociface

PACKS=pociface

SOURCES = iface_parser.ml
THREADS=yes
RESULT=iface_parser

all: nc

include $(OCAMLMAKEFILE)